# Generated by Django 2.2.1 on 2019-05-21 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('TEM', 'Temperatura'), ('HUM', 'Humedad'), ('GAS', 'Gas'), ('LLA', 'Llama')], max_length=3, verbose_name='Tipo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('valor_max_tem', models.SmallIntegerField(verbose_name='Valor Máximo de Temperatura')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='lectura_sensores',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de lectura')),
                ('valor', models.SmallIntegerField(default=0, verbose_name='Valor de la lectura')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete='Creado por', to=settings.AUTH_USER_MODEL)),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectura_sensores', to='cpd.sensor')),
            ],
            options={
                'verbose_name': 'Lectura sensor',
                'verbose_name_plural': 'Lectura sensores',
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='incidencia',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_de_accion', models.IntegerField(verbose_name='Valor de acción')),
                ('descripcion', models.TextField(default='Ha saltado una alarma', verbose_name='Descripción')),
                ('estado_motor', models.BooleanField(verbose_name='Estado de los motores')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete='Creado por', to=settings.AUTH_USER_MODEL)),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='cpd.sensor')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-id'],
            },
        ),
    ]
