# Generated by Django 2.2.1 on 2019-05-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='valor_max_tem',
            field=models.SmallIntegerField(null=True, verbose_name='Valor Máximo de Temperatura'),
        ),
    ]
