# Generated by Django 2.2.1 on 2019-05-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpd', '0003_auto_20190523_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='cpd.Sensor'),
        ),
        migrations.AlterField(
            model_name='lectura_sensores',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectura_sensores', to='cpd.Sensor'),
        ),
    ]
