# Generated by Django 2.2.1 on 2019-05-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpd', '0004_auto_20190523_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='cpd.Sensor'),
        ),
        migrations.AlterField(
            model_name='lectura_sensores',
            name='num',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de lectura'),
        ),
        migrations.AlterField(
            model_name='lectura_sensores',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectura_sensores', to='cpd.Sensor'),
        ),
    ]
